title: Antonio Barajas # your name (or website title) here
logo: "/images/KDC_Mix_icon_1_1.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I do stuff sometimes
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
